export const types = {
  GET_LOGIN: 'GET_LOGIN',
  GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
  GET_LOGIN_FAILURE: 'GET_LOGIN_FAILURE',
  GET_LOGIN_RESET: 'GET_LOGIN_RESET',

  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
  GET_PRODUCT_RESET: 'GET_PRODUCT_RESET',
};
